<a href="https://colab.research.google.com/github/RSoto3/MineriaTaller1/blob/main/TallerMineria1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lectura de datos

In [ ]:
import numpy as np
import pandas as pd
# Para visualizacion
import matplotlib.pyplot as plt
# Para expresiones regulares
import re
# Para manejar strings
import string
# Para expresiones matematicas
import math

from google.colab import drive
drive.mount('/content/drive')

# importando el DataSet
df=pd.read_csv('/content/drive/MyDrive/Archivos mineria /Licencias_Medicas_2022t2.txt', sep = "|",names= ['Codigo Isapre','Fecha Informacion','Run Trabajador','Fecha emision licencia','Numero de dias','Fecha inicio reposo','Edad trabajador','Sexo trabajador','Actividad laboral','Ocupacion','Tipo de licencia','Caracteristicas del reposo','Run profesional','Tipo profesional','Tipo licencia segun contraloria','Numero de dias autorizados','Diagnostico principal','Tipo de resolucion','Periodo','Reposo autorizado','Derecho a subsidio','Fecha recepcion isapre','Fecha resolucion isapre','Fecha recepcion empleador','Region','Calidad Trabajador','Entidad pagadora','Numero dias a pagar','Monto subsidio liquido','Monto aporte previsional isapre','Fecha de inicio del pago','Recuperabilidad','Fecha de concepcion','Monto aporte previsional de pensiones','Otros diagnosticos','Run identificacion del hijo','Lugar reposo','Causa rechazo o modificacion','Numero de dias previos autorizados','Fecha primera afiliacion entidad previsional','Fecha contrato de trabajo','Monto base calculo subsidio','Rut Empleador','Fecha nacimiento hijo','borrar'])
df.isnull().sum()
print("Shape of data=>",df.shape)
df2 = df.copy()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (34) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

Shape of data=> (573493, 45)

#Data faltante

In [ ]:
#DataFrame original
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573493 entries, 0 to 573492
Data columns (total 45 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Codigo Isapre                                 573493 non-null  int64
 1   Fecha Informacion                             573493 non-null  object
 2   Run Trabajador                                573493 non-null  int64
 3   Fecha emision licencia                        573493 non-null  object
 4   Numero de dias                                573493 non-null  int64
 5   Fecha inicio reposo                           573493 non-null  object
 6   Edad trabajador                               573493 non-null  object
 7   Sexo trabajador                               573493 non-null  object
 8   Actividad laboral                             573493 non-null  object
 9   Ocupacion                                     573493 non-null  object
 10  Tipo de licencia                              573493 non-null  object
 11  Caracteristicas del reposo                    573493 non-null  object
 12  Run profesional                               573493 non-null  int64
 13  Tipo profesional                              573493 non-null  object
 14  Tipo licencia segun contraloria               573493 non-null  object
 15  Numero de dias autorizados                    573493 non-null  int64
 16  Diagnostico principal                         561751 non-null  object
 17  Tipo de resolucion                            573493 non-null  object
 18  Periodo                                       573493 non-null  object
 19  Reposo autorizado                             573493 non-null  object
 20  Derecho a subsidio                            573493 non-null  object
 21  Fecha recepcion isapre                        573493 non-null  object
 22  Fecha resolucion isapre                       573493 non-null  object
 23  Fecha recepcion empleador                     573493 non-null  object
 24  Region                                        573493 non-null  int64
 25  Calidad Trabajador                            573493 non-null  object
 26  Entidad pagadora                              573493 non-null  object
 27  Numero dias a pagar                           573493 non-null  int64
 28  Monto subsidio liquido                        573493 non-null  int64
 29  Monto aporte previsional isapre               573493 non-null  int64
 30  Fecha de inicio del pago                      573493 non-null  object
 31  Recuperabilidad                               573493 non-null  object
 32  Fecha de concepcion                           573493 non-null  int64
 33  Monto aporte previsional de pensiones         573493 non-null  int64
 34  Otros diagnosticos                            8299 non-null    object
 35  Run identificacion del hijo                   573493 non-null  int64
 36  Lugar reposo                                  573493 non-null  object
 37  Causa rechazo o modificacion                  573493 non-null  object
 38  Numero de dias previos autorizados            573493 non-null  int64
 39  Fecha primera afiliacion entidad previsional  573493 non-null  object
 40  Fecha contrato de trabajo                     573493 non-null  object
 41  Monto base calculo subsidio                   573493 non-null  int64
 42  Rut Empleador                                 573493 non-null  int64
 43  Fecha nacimiento hijo                         573493 non-null  int64
 44  borrar                                        0 non-null       float64
dtypes: float64(1), int64(16), object(28)
memory usage: 196.9+ MB

In [ ]:
# Data faltante con porcentaje:

total = df.isnull().sum().sort_values(ascending = False)
percent = (df.isnull().sum() / df.isnull().count()).sort_values(ascending = False)
missing_data = pd.concat([total, percent], axis = 1, keys = ['Total', 'Porcentaje'])
missing_data.head(20)

                                               Total  Porcentaje
borrar                                        573493    1.000000
Otros diagnosticos                            565194    0.985529
Diagnostico principal                          11742    0.020475
Fecha nacimiento hijo                              0    0.000000
Fecha de concepcion                                0    0.000000
Calidad Trabajador                                 0    0.000000
Entidad pagadora                                   0    0.000000
Numero dias a pagar                                0    0.000000
Monto subsidio liquido                             0    0.000000
Monto aporte previsional isapre                    0    0.000000
Fecha de inicio del pago                           0    0.000000
Recuperabilidad                                    0    0.000000
Monto aporte previsional de pensiones              0    0.000000
Rut Empleador                                      0    0.000000
Fecha recepcion empleador                          0    0.000000
Run identificacion del hijo                        0    0.000000
Lugar reposo                                       0    0.000000
Causa rechazo o modificacion                       0    0.000000
Numero de dias previos autorizados                 0    0.000000
Fecha primera afiliacion entidad previsional       0    0.000000

In [226]:
df.isnull().sum()

Codigo Isapre                                        0
Fecha Informacion                                    0
Run Trabajador                                       0
Fecha emision licencia                               0
Numero de dias                                       0
Fecha inicio reposo                                  0
Edad trabajador                                      0
Sexo trabajador                                      0
Actividad laboral                                    0
Ocupacion                                            0
Tipo de licencia                                     0
Caracteristicas del reposo                           0
Run profesional                                      0
Tipo profesional                                     0
Tipo licencia segun contraloria                      0
Numero de dias autorizados                           0
Diagnostico principal                            11742
Tipo de resolucion                                   0
Periodo                                              0
Reposo autorizado                                    0
Derecho a subsidio                                   0
Fecha recepcion isapre                               0
Fecha resolucion isapre                              0
Fecha recepcion empleador                            0
Region                                               0
Calidad Trabajador                                   0
Entidad pagadora                                     0
Numero dias a pagar                                  0
Monto subsidio liquido                               0
Monto aporte previsional isapre                      0
Fecha de inicio del pago                             0
Recuperabilidad                                      0
Fecha de concepcion                                  0
Monto aporte previsional de pensiones                0
Otros diagnosticos                              565194
Run identificacion del hijo                          0
Lugar reposo                                         0
Causa rechazo o modificacion                         0
Numero de dias previos autorizados                   0
Fecha primera afiliacion entidad previsional         0
Fecha contrato de trabajo                            0
Monto base calculo subsidio                          0
Rut Empleador                                        0
Fecha nacimiento hijo                                0
borrar                                          573493
dtype: int64

#Eliminacion de columnas y de filas

In [ ]:
#Eliminacion de columnas que no se utilizarán
df2 = df2.drop('borrar', axis=1)
df2 = df2.drop('Edad trabajador', axis=1)
df2 = df2.drop('Run profesional', axis=1)
df2 = df2.drop('Sexo trabajador', axis=1)
df2 = df2.drop('Tipo profesional', axis=1)
df2 = df2.drop('Derecho a subsidio', axis=1)
df2 = df2.drop('Ocupacion', axis=1)
df2 = df2.drop('Region', axis=1)
df2 = df2.drop('Monto subsidio liquido', axis=1)
df2 = df2.drop('Monto aporte previsional isapre', axis=1)
df2 = df2.drop('Monto aporte previsional de pensiones', axis=1)
df2 = df2.drop('Fecha primera afiliacion entidad previsional', axis=1)
df2 = df2.drop('Fecha contrato de trabajo', axis=1)
df2 = df2.drop('Monto base calculo subsidio', axis=1)
df2 = df2.drop('Fecha nacimiento hijo', axis=1)
df2 = df2.drop('Calidad Trabajador', axis=1)
df2 = df2.drop('Numero de dias previos autorizados', axis=1)
df2 = df2.drop('Fecha de concepcion', axis=1)
df2 = df2.drop('Actividad laboral', axis=1)
df2 = df2.drop('Rut Empleador', axis=1)
df2 = df2.drop('Run Trabajador', axis=1)
df2 = df2.drop('Run identificacion del hijo', axis=1)
df2 = df2.drop('Fecha de inicio del pago', axis=1)
df2 = df2.drop('Fecha Informacion', axis=1)
df2 = df2.drop('Otros diagnosticos', axis=1)
df2 = df2[df2['Diagnostico principal'].notna()]
df2 = df2.drop('Fecha resolucion isapre', axis=1)

In [ ]:
#Nuevo DataFrame
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 561751 entries, 1 to 573492
Data columns (total 19 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Codigo Isapre                    561751 non-null  int64
 1   Fecha emision licencia           561751 non-null  object
 2   Numero de dias                   561751 non-null  int64
 3   Fecha inicio reposo              561751 non-null  object
 4   Tipo de licencia                 561751 non-null  object
 5   Caracteristicas del reposo       561751 non-null  object
 6   Tipo licencia segun contraloria  561751 non-null  object
 7   Numero de dias autorizados       561751 non-null  int64
 8   Diagnostico principal            561751 non-null  object
 9   Tipo de resolucion               561751 non-null  object
 10  Periodo                          561751 non-null  object
 11  Reposo autorizado                561751 non-null  object
 12  Fecha recepcion isapre           561751 non-null  object
 13  Fecha recepcion empleador        561751 non-null  object
 14  Entidad pagadora                 561751 non-null  object
 15  Numero dias a pagar              561751 non-null  int64
 16  Recuperabilidad                  561751 non-null  object
 17  Lugar reposo                     561751 non-null  object
 18  Causa rechazo o modificacion     561751 non-null  object
dtypes: int64(4), object(15)
memory usage: 85.7+ MB

#Separadores

In [ ]:
#separar Fecha emision licencia
df2["Fecha emision licencia"] = df2.apply(
    lambda x:
          str(x["Fecha emision licencia"]).split(sep = 't'),
          axis = 1
)
df2["Año emision licencia"] = df2.apply(
    lambda x:
        str(x["Fecha emision licencia"])[2:6],
        axis = 1
)
df2["Año emision licencia"] = df2.apply(
        lambda x:
            x["Año emision licencia"] if ((str(x["Año emision licencia"][0])).isnumeric() & (str(x["Año emision licencia"][1])).isnumeric()) else "Quitar"
            , axis = 1
    )


df2["Trimestre emision licencia"] = df2.apply(
    lambda x:
        str(x["Fecha emision licencia"])[-3:-2],
        axis = 1
)

df2 = df2.drop(columns = "Fecha emision licencia")

In [ ]:
#separar Fecha inicio reposo
df2["Fecha inicio reposo"] = df2.apply(
    lambda x:
          str(x["Fecha inicio reposo"]).split(sep = 't'),
          axis = 1
)
df2["Año emision reposo"] = df2.apply(
    lambda x:
        str(x["Fecha inicio reposo"])[2:6],
        axis = 1
)
df2["Año emision reposo"] = df2.apply(
        lambda x:
            x["Año emision reposo"] if ((str(x["Año emision reposo"][0])).isnumeric() & (str(x["Año emision reposo"][1])).isnumeric()) else "Quitar"
            , axis = 1
    )


df2["Trimestre emision reposo"] = df2.apply(
    lambda x:
        str(x["Fecha inicio reposo"])[-3:-2],
        axis = 1
)

df2 = df2.drop(columns = "Fecha inicio reposo")

In [ ]:
#separar Fecha recepcion isapre
df2["Fecha recepcion isapre"] = df2.apply(
    lambda x:
          str(x["Fecha recepcion isapre"]).split(sep = 't'),
          axis = 1
)
df2["Año recepcion isapre"] = df2.apply(
    lambda x:
        str(x["Fecha recepcion isapre"])[2:6],
        axis = 1
)
df2["Año recepcion isapre"] = df2.apply(
        lambda x:
            x["Año recepcion isapre"] if ((str(x["Año recepcion isapre"][0])).isnumeric() & (str(x["Año recepcion isapre"][1])).isnumeric()) else "Quitar"
            , axis = 1
    )


df2["Trimestre recepcion isapre"] = df2.apply(
    lambda x:
        str(x["Fecha recepcion isapre"])[-3:-2],
        axis = 1
)

df2 = df2.drop(columns = "Fecha recepcion isapre")

In [ ]:
#separar Fecha recepcion empleador
df2["Fecha recepcion empleador"] = df2.apply(
    lambda x:
          str(x["Fecha recepcion empleador"]).split(sep = 't'),
          axis = 1
)
df2["Año recepcion empleador"] = df2.apply(
    lambda x:
        str(x["Fecha recepcion empleador"])[2:6],
        axis = 1
)
df2["Año recepcion empleador"] = df2.apply(
        lambda x:
            x["Año recepcion empleador"] if ((str(x["Año recepcion empleador"][0])).isnumeric() & (str(x["Año recepcion empleador"][1])).isnumeric()) else "Quitar"
            , axis = 1
    )


df2["Trimestre recepcion empleador"] = df2.apply(
    lambda x:
        str(x["Fecha recepcion empleador"])[-3:-2],
        axis = 1
)

df2 = df2.drop(columns = "Fecha recepcion empleador")

In [ ]:
#Nuevo DataFrame
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 561751 entries, 1 to 573492
Data columns (total 23 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Codigo Isapre                    561751 non-null  int64
 1   Numero de dias                   561751 non-null  int64
 2   Tipo de licencia                 561751 non-null  object
 3   Caracteristicas del reposo       561751 non-null  object
 4   Tipo licencia segun contraloria  561751 non-null  object
 5   Numero de dias autorizados       561751 non-null  int64
 6   Diagnostico principal            561751 non-null  object
 7   Tipo de resolucion               561751 non-null  object
 8   Periodo                          561751 non-null  object
 9   Reposo autorizado                561751 non-null  object
 10  Entidad pagadora                 561751 non-null  object
 11  Numero dias a pagar              561751 non-null  int64
 12  Recuperabilidad                  561751 non-null  object
 13  Lugar reposo                     561751 non-null  object
 14  Causa rechazo o modificacion     561751 non-null  object
 15  Año emision licencia             561751 non-null  object
 16  Trimestre emision licencia       561751 non-null  object
 17  Año emision reposo               561751 non-null  object
 18  Trimestre emision reposo         561751 non-null  object
 19  Año recepcion isapre             561751 non-null  object
 20  Trimestre recepcion isapre       561751 non-null  object
 21  Año recepcion empleador          561751 non-null  object
 22  Trimestre recepcion empleador    561751 non-null  object
dtypes: int64(4), object(19)
memory usage: 102.9+ MB

#Convertir object a int

In [ ]:
#Eliminacion de filas con datos erroneos
df2.drop(df2.index[df2['Año recepcion empleador'] == 3000], inplace = True)
df2.drop(df2.index[df2['Año recepcion empleador'] == 1800], inplace = True)
df2.drop(df2.index[df2['Año recepcion empleador'] == 2023], inplace = True)

In [ ]:
#Codigo para convertir los object a int
df2['Año emision licencia'] = df2['Año emision licencia'].astype(str).astype(int)
df2['Año emision reposo'] = df2['Año emision reposo'].astype(str).astype(int)
df2['Trimestre emision licencia'] = df2['Trimestre emision licencia'].astype(str).astype(int)
df2['Trimestre emision reposo'] = df2['Trimestre emision reposo'].astype(str).astype(int)
df2['Año recepcion isapre'] = df2['Año recepcion isapre'].astype(str).astype(int)
df2['Trimestre recepcion isapre'] = df2['Trimestre recepcion isapre'].astype(str).astype(int)
df2['Año recepcion empleador'] = df2['Año recepcion empleador'].astype(str).astype(int)
df2['Trimestre recepcion empleador'] = df2['Trimestre recepcion empleador'].astype(str).astype(int)

In [ ]:
#Nuevo DataFrame
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 554967 entries, 1 to 573492
Data columns (total 23 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Codigo Isapre                    554967 non-null  int64
 1   Numero de dias                   554967 non-null  int64
 2   Tipo de licencia                 554967 non-null  object
 3   Caracteristicas del reposo       554967 non-null  object
 4   Tipo licencia segun contraloria  554967 non-null  object
 5   Numero de dias autorizados       554967 non-null  int64
 6   Diagnostico principal            554967 non-null  object
 7   Tipo de resolucion               554967 non-null  object
 8   Periodo                          554967 non-null  object
 9   Reposo autorizado                554967 non-null  object
 10  Entidad pagadora                 554967 non-null  object
 11  Numero dias a pagar              554967 non-null  int64
 12  Recuperabilidad                  554967 non-null  object
 13  Lugar reposo                     554967 non-null  object
 14  Causa rechazo o modificacion     554967 non-null  object
 15  Año emision licencia             554967 non-null  int64
 16  Trimestre emision licencia       554967 non-null  int64
 17  Año emision reposo               554967 non-null  int64
 18  Trimestre emision reposo         554967 non-null  int64
 19  Año recepcion isapre             554967 non-null  int64
 20  Trimestre recepcion isapre       554967 non-null  int64
 21  Año recepcion empleador          554967 non-null  int64
 22  Trimestre recepcion empleador    554967 non-null  int64
dtypes: int64(12), object(11)
memory usage: 101.6+ MB

#Variables Binarias

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Diagnostico principal'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Diagnostico principal'])

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Tipo de resolucion'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Tipo de resolucion'])

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Periodo'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Periodo'])

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Reposo autorizado'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Reposo autorizado'])

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Entidad pagadora'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Entidad pagadora'])

In [ ]:
#Reemplazamos los valores SI y NO por 1 y 0

df2['Recuperabilidad'] = df2['Recuperabilidad'].map({'SI': 1, 'NO': 0})

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Lugar reposo'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Lugar reposo'])

In [ ]:
# Creamos las variables binarias
dummies = pd.get_dummies(df2['Causa rechazo o modificacion'])
dummies.head()

# Añadimos las variables binarias al DataFrame
df2 = pd.concat([df2, dummies], axis = 1)

# Eliminamos la vairable original race
df2 = df2.drop(columns=['Causa rechazo o modificacion'])

In [222]:
df2

,Codigo Isapre,Numero de dias,Numero de dias autorizados,Numero dias a pagar,Año emision licencia,Trimestre emision licencia,Año emision reposo,Trimestre emision reposo,Año recepcion isapre,Trimestre recepcion isapre,Año recepcion empleador,Trimestre recepcion empleador,A00-B99,C00-D48,D50-D89,E00-E90,F00-F99,G00-G99,H00-H59,H60-H95,I00-I99,J00-J99,K00-K93,L00-L99,M00-M99,N00-N99,O00-O99,P00-P96,Q00-Q99,R00-R99,S00-T98,U00-U99,V01-Y98,Z00-Z99,Ampliese,Autoricese,Rechacese,Reducese,Continuacion,Primera,Rep. Par. Man.,Rep. Par. Noc.,Rep. Par. Tar.,Reposo Total,Z. Sin Clasificar,CCAF,Empleador,Isapre,Mutual,Servicio de Salud,Z. Sin Clasificar,NO,SI,Z. Sin Clasificar,Hospital,Otro Domicilio,Su Domicilio,Z. Sin Clasificar,Diagnostico Irrecuperable,Fuera de Plazo,Incumplimiento reposo,Otro,Reposo Injustificado,Z. Sin Clasificar
count,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.00000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000,554967.000000
mean,86.358068,12.896742,7.631547,5.312255,2021.999382,1.937099,2021.998969,1.934162,2021.999975,1.966036,2021.999135,1.948164,0.033207,0.019716,0.001728,0.008056,0.232527,0.023569,0.010091,0.010404,0.013192,0.125687,0.059712,0.005991,0.117706,0.023744,0.016109,0.004588,0.004447,0.020318,0.063442,0.176443,0.002155,0.027167,0.000076,0.644970,0.217885,0.137069,0.242052,0.757948,0.001101,0.000308,0.002600,0.995987,0.000004,0.000031,0.192464,0.803086,0.004099,0.000054,0.000267,0.004748,0.995227,0.000025,0.00237,0.027609,0.966798,0.003224,0.005177,0.005826,0.000238,0.136464,0.207328,0.644968
std,15.387173,13.078085,11.658614,11.051810,0.043802,0.246607,0.047372,0.255416,0.006003,0.181425,0.092258,0.223798,0.179178,0.139024,0.041534,0.089395,0.422444,0.151702,0.099944,0.101469,0.114095,0.331496,0.236952,0.077172,0.322260,0.152250,0.125895,0.067577,0.066538,0.141087,0.243756,0.381197,0.046373,0.162571,0.008699,0.478523,0.412809,0.343921,0.428326,0.428326,0.033163,0.017551,0.050925,0.063220,0.001898,0.005535,0.394236,0.397667,0.063895,0.007352,0.016328,0.068742,0.068924,0.005023,0.04862,0.163849,0.179164,0.056685,0.071764,0.076103,0.015421,0.343281,0.405393,0.478523
min,63.000000,1.000000,0.000000,0.000000,2002.000000,1.000000,2004.000000,1.000000,2020.000000,1.000000,2002.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,78.000000,4.000000,1.000000,0.000000,2022.000000,2.000000,2022.000000,2.000000,2022.000000,2.000000,2022.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,81.000000,7.000000,4.000000,0.000000,2022.000000,2.000000,2022.000000,2.000000,2022.000000,2.000000,2022.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,99.000000,15.000000,7.000000,6.000000,2022.000000,2.000000,2022.000000,2.000000,2022.000000,2.000000,2022.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,108.000000,320.000000,126.000000,126.000000,2022.000000,4.000000,2022.000000,4.000000,2022.000000,4.000000,2022.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000